### PR TITLE
css

### PR DESCRIPTION
**Pull request by ganeshdeveloper1**

### CODE REVIEW

**Comment by devRabbani** [comment]
what did you change???
GIve description

**Comment by devRabbani** [comment]
I will reject this if you dont follow rule.
@rohittiwari833 

- [ ]  Nehi
- [ ]  Haa

**Comment by devRabbani** [comment]
Bhai response do.....kaha ho???
@rohittiwari833

**Comment by ganeshdeveloper1** [comment]
What happened?

**Comment by devRabbani** [comment]
Rejected

**Pull request closed without merging**
